#!/bin/sh
cd ~
# user preferred settings

#cursor size
export XCURSOR_SIZE=6

# text editor
export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/micro

#browser
export BROWSER=brave
#terminal
export TERM=kitty
#mail
export MAIL=thunderbird

# check /usr/local/bin/hyprstart 
